"""Initial migration.

Revision ID: 41c70ff97209
Revises:
Create Date: 2025-07-21 23:39:54.237877

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "41c70ff97209"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
