# GitHub Actions CI Pipeline for FastAPI Todo App
name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: todo_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user -d todo_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Load environment variables from pytest.env
        uses: falti/dotenv-action@v1.1.4
        with:
          path: pytest.env
      - name: Install uv
        run: |
          pip install uv
      - name: Install project dependencies with uv
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e .
          uv pip install pytest pytest-cov pre-commit alembic
      - name: echo env variables
        run: |
          echo "DATABASE_URL: $DATABASE_URL"
          echo "DATABASE_HOST: $DATABASE_HOST"
          echo "DATABASE_PORT: $DATABASE_PORT"
          echo "DATABASE_NAME: $DATABASE_NAME"
          echo "DATABASE_USER: $DATABASE_USER"
          echo "DATABASE_PASSWORD: $DATABASE_PASSWORD"
          echo "APP_TITLE: $APP_TITLE"
          echo "APP_DESCRIPTION: $APP_DESCRIPTION"
          echo "APP_VERSION: $APP_VERSION"
          echo "APP_NAME: $APP_NAME"
          echo "DEBUG: $DEBUG"
      - name: Run migrations
        run: |
          source .venv/bin/activate
          alembic -x url=$DATABASE_URL_ALEMBIC upgrade head
      - name: Run pytest with coverage
        run: |
          source .venv/bin/activate
          pytest -s --cov=app --cov-report=xml --cov-report=term tests/
      - name: Check coverage >= 80%
        run: |
          source .venv/bin/activate
          coverage report --fail-under=80
      - name: Run pre-commit checks
        run: |
          source .venv/bin/activate
          pre-commit run --all-files
